version: "3.8"

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passkey}
            POSTGRES_DB: ${POSTGRES_DB:-cdscb}
        ports:
            - "5432:5432"

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
